config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root to: 'pages#home'
  get "/splash", to: "pages#splash"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :update,:edit, :destroy] do
    resources :contacts, only: [:create, :update, :destroy]
  end

  resources :incidents, only: [:new, :create, :edit, :update, :destroy] do
    get "/survey_success", to: "pages#survey_success"
  end

  resources :journeys, only:[:create, :show] do
    member do
      post :broadcast
      get :finish
    end
    resources :incidents, only: [:index, :edit, :update]
  end

  resources :ratings, only: [:create, :index]

  resources :messages, only: :create

  get "/calling", to: "pages#calling"
  get "/navigation", to: "pages#navigation"
  get "/uikit", to: "pages#uikit"
  get "/survey_success", to: "pages#survey_success"
  get "/emergency_number/:iso", to: "emergency_numbers#show"
end

app/models/incident.rb
class Incident < ApplicationRecord
  attr_accessor :location_needs_validation
  attr_accessor :crime_needs_validation
  # validates :location, presence: true, if: -> {location_needs_validation}


  CRIME_TYPES = ["Derogatory comments", "Theft", "Stalking/following", "Verbally threatening behavior", "Unwanted physical contact", "Sexual assault", "Violent (nonsexual) assault", "Other"]
  belongs_to :user, optional: true
  belongs_to :journey, optional: true
  geocoded_by :location
  after_validation :geocode, if: :geocode?
  after_validation :reverse_geocode, if: :reverse_geocode?
  validates :time, presence: true
  validates :date, presence: true
  # validates :location, presence: true
  # validates :crime, inclusion: {in: CRIME_TYPES} # REQUIRED:TRUE IN SIMPLE FORM ON SURVEY DOES THIS ALREADY

  def reverse_geocode
    self.location = Geocoder.search([latitude, longitude]).first.address
  end

  def geocode?
    location && will_save_change_to_location?
  end

  def reverse_geocode?
    !geocode?
  end
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController

  def index
    @journey = Journey.find(params[:journey_id])
    @incidents = @journey.incidents
    if @incidents.empty?
      redirect_to root_path
    end
  end

  def new
    @incident = Incident.new
  end

  def create
    @journey = Journey.find_by(id: params[:journey_id])
    @incident = Incident.new(incident_params)

    return if validating_location
    return if validating_crime

    if @journey
      @incident.date = Date.today
      @incident.latitude = @journey.current_location["latitude"]
      @incident.longitude = @journey.current_location["longitude"]
      @incident.time = DateTime.now.to_s(:time)
      @incident.journey = @journey
      @incident.user = @journey.user
    else
      @incident.user = current_user
    end

    respond_to do |format|
      if @incident.save
        format.html { redirect_to incident_survey_success_path(@incident) } #change to redirect to survey
        format.text { render partial: 'shared/incident_flash', locals: { message: "Location and time saved. We'll ask for more info later." }, formats: [:html] }
      else
        format.html { render :new } #change to redirect to same page with an error
        format.text { head 422 }
      end
    end
  end

  def edit
    @incident = Incident.find(params[:id])
  end

  def update
    @incident = Incident.find(params[:id])
    return if validating_update_crime

    @incident.update(incident_params)


    if @incident.save
      redirect_to incident_survey_success_path(@incident)
    else
      render :edit
    end
  end

  def destroy
    @incident = Incident.find(params[:id])
    @journey = @incident.journey
    @incident.destroy
    redirect_to journey_incidents_path(@journey)
  end

  private

  def validating_location
    if params[:incident][:location_needs_validation] == "true" && !@incident.location.present?
      @incident.errors.add(:location, "Location must be present.")
      render :new
      return true
    end
    return false
  end

  def validating_update_crime
    if params[:incident][:crime_needs_validation] == "true" && !Incident::CRIME_TYPES.include?(params[:incident][:crime])
      @incident.errors.add(:crime, "must be included in the list.")
      render :edit
      return true
    end
    return false
  end

  def validating_crime
    if params[:incident][:crime_needs_validation] == "true" && !Incident::CRIME_TYPES.include?(@incident.crime)
      @incident.errors.add(:crime, "must be included in the list.")
      render :new
      return true
    end
    return false
  end

  def incident_params
    params.require(:incident).permit(:date, :time, :latitude, :longitude, :location, :crime, :description)
  end
end

app/views/incidents/edit.html.erb
<div class="survey-container">
  <div class="head-message">
    <div class="title-exitbtn">
      <h1>Tell us what happened</h1>
      <%= link_to root_path do %>
      <i class="fas fa-times-circle" style="font-size: 25px; margin-bottom: 8px;"></i>
      <% end %>
    </div>
    <p>If you feel comfortable, please complete this optional survey to help us get other users home safely. <br>Your data will be collected anonymously, but it will be displayed on the map so other users know which areas to avoid.</p>
  </div>
  <%= simple_form_for @incident do |f| %>
   <%= f.hidden_field :crime_needs_validation, value: true %>
    <div class="survey-form">
      <div class="custom-field">
        <h3>What was the nature of the incident?</h3>
        <p>Select the category that most closely matches the incident. If multiple categories apply, select the one that you feel was the most serious. </p>
        <%= f.input :crime, collection: Incident::CRIME_TYPES, label: false, include_blank: "Select crime type", input_html: {class: "form-inputs"} %>
      </div>
      <div class="custom-field">
        <h3>Additional description</h3>
        <p>If you have any other information that you want to share, please feel free to write it here (ie., what did the person look like?)</p>
        <%= f.input :description, as: :text, input_html: {rows: 5, class: "form-inputs"}, label: false %>
      </div>
      <%= f.submit 'Submit my survey response', class: "custom-submit" %>
    </div>
  <% end %>
</div>

app/views/incidents/index.html.erb
<%# Should only go on this page IF incident flagged. Put if else on I'm home button %>
  <%# Should redirect to this page if more than one incident %>

<div class = "incidents-index-wrapper">
  <div class = 'incident-index-headers'>
    <h1> Flagged incidents </h1>
    <p> Please click edit to add information about the incidents you flagged this journey - your data will only be used on our map if you complete this step. </p>
  </div>

  <%= link_to root_path do %>
    <div class = 'incident-index-exit-button'>
      <%# Cross button icon %>
      <i class="fas fa-times-circle" style="font-size: 25px; margin-bottom: 8px;"></i>
    </div>
  <% end %>

  <% @incidents.each do |incident| %>
    <div class = "incident-card">
      <%# Flag icon %>
      <div class = "index-card-title-and-flag">
        <span class="iconify button-flag" data-icon="el:flag-alt" style="color: #29353D;"></span>
        <h2> Incident reported at: </h2>
      </div>
      <div class = "index-card-content">
        <p><strong> Location: </strong> <%= incident.location %> </p>
        <p><strong> Time: </strong> <%= incident.time.strftime("%l:%M%p") %> </p>
      </div>

      <%# Edit button %>
      <div class = "incident-edit-button" >
        <%= link_to edit_incident_path(incident) do %>
          <i class="far fa-edit"></i>
        <% end %>
      </div>

      <%# Delete button %>
      <div class = "incident-destroy-button">
        <%= link_to incident_path(incident), method: :delete, data: { confirm: "Are you sure you want to delete this incident?" } do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      </div>

      <%# Reminder  %>
      <% if incident.description.present? %>
        <div class = "incident-reminder-green">
          <p> You've already added a description to this incident. </p>
          <%# <i class="far fa-check-circle"></i> %>
        </div>
      <% end %>

    </div>
  <% end %>

    <%= link_to root_path do %>
    <div class = 'incident-index-done-button'>
       <button class="button-blue done-index-button">I'm done, take me back home</button>
    </div>
  <% end %>
</div>

app/views/incidents/new.html.erb
<div class="survey-container">
  <div class="head-message">
    <div class="title-exitbtn">
      <h1>Tell us what happened</h1>
      <%= link_to root_path do %>
      <i class="fas fa-times-circle" style="font-size: 25px; margin-bottom: 8px;"></i>
      <% end %>
    </div>
    <p>If you feel comfortable, please complete this optional survey to help us get other users home safely. <br>Your data will be collected anonymously, but it will be displayed on the map so other users know which areas to avoid.</p>
  </div>
  <%= simple_form_for @incident do |f| %>
    <%= f.hidden_field :location_needs_validation, value: true %>
     <%= f.hidden_field :crime_needs_validation, value: true %>
    <div class="survey-form">
      <div class="custom-field">
      <h3>Where did it happen?</h3>
      <%# Autocomplete location %>
      <%= f.input :location, input_html: { class: "form-inputs", id: "survey-input-location" }, placeholder: "Location of the incident", label: false %>
      </div>
      <div class="custom-field">
        <h3>What date did it happen on?</h3>
        <%= f.input :date, label: false, required: true, input_html: {class: "form-inputs custom-date"}, wrapper_html: {class: "time-wrapper no-paragraph"} %>
      </div class="custom-field">
      <div>
        <h3>What time did it happen at?</h3>
        <p>If you aren’t sure, choose the nearest estimate.</p>
        <%= f.input :time, label: false, required: true, input_html: {class: "form-inputs custom-date"}, wrapper_html: {class: "time-wrapper"} %>
      </div>
      <div class="custom-field">
        <h3>What was the nature of the incident?</h3>
        <p>Select the category that most closely matches the incident. If multiple categories apply, select the one that you feel was the most serious. </p>
        <%= f.input :crime, collection: Incident::CRIME_TYPES, label: false, include_blank: "Select crime type", input_html: {class: "form-inputs"} %>
      </div>
      <div class="custom-field">
        <h3>Additional description:</h3>
        <p>If you have any other information that you want to share, please feel free to write it here (ie., what did the person look like?)</p>
        <%= f.input :description, as: :text, input_html: {rows: 5, class: "form-inputs"}, label: false %>
      </div>
      <%= f.submit 'Submit my survey response', class: "custom-submit" %>
    </div>
  <% end %>
</div>