config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root to: 'pages#home'
  get "/splash", to: "pages#splash"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :update,:edit, :destroy] do
    resources :contacts, only: [:create, :update, :destroy]
  end

  resources :incidents, only: [:new, :create, :edit, :update, :destroy] do
    get "/survey_success", to: "pages#survey_success"
  end

  resources :journeys, only:[:create, :show] do
    member do
      post :broadcast
      get :finish
    end
    resources :incidents, only: [:index, :edit, :update]
  end

  resources :ratings, only: [:create, :index]

  resources :messages, only: :create

  get "/calling", to: "pages#calling"
  get "/navigation", to: "pages#navigation"
  get "/uikit", to: "pages#uikit"
  get "/survey_success", to: "pages#survey_success"
  get "/emergency_number/:iso", to: "emergency_numbers#show"
end

app/views/shared/_directions.html.erb
<div id="directions" class = "h-100 directions-hide"
  data-map-target="directions"
  data-navigation-ui-target="directions"
  data-origin = "<%= @origin.to_json %>"
  data-incidents = "<%= @incidents.to_json %>"
  data-avoid = "<%= @incidents_avoid %>"
  data-destination = "<%= @destination.to_json %>"
  data-here-api-key="<%= ENV['HERE_API_KEY'] %>">
  <h2>Directions</h2>
</div>

app/views/shared/_directions_toggle.html.erb
<div class = "directions-toggle-div">
  <i class="fas fa-list-ul" data-navigation-ui-target = "directionButton"></i>
  <i class="fas fa-location-arrow d-none" data-navigation-ui-target = "arrowButton"></i>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_incident_flash.html.erb
  <div class="alert alert-info alert-dismissible fade show m-1 alert-gg" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

app/views/shared/_logo.html.erb
<%# <div class = "logo-container"> %>
  <%# <div class = "brand-logo">
    <%= image_tag("splash_page.png") %>
  <%# </div> %>
  <%# <p class = "brand-name"> Go Girl </p> %>
<%# </div> %>

app/views/shared/_map.html.erb
<div id="map" class = "h-100"
  data-navigation-ui-target="map"
  data-map-target="map"
  data-journey-id="<%= @journey.id %>"
  data-is-owner="<%= user_signed_in? && current_user == @journey.user %>"
  data-origin = "<%= @origin.to_json %>"
  data-incidents = "<%= @incidents.to_json %>"
  data-avoid = "<%= @incidents_avoid %>"
  data-boxes = "<%= @cluster_objects.to_json %>"
  data-destination = "<%= @destination.to_json %>"
  data-here-api-key="<%= ENV['HERE_API_KEY'] %>">
  <% if signed_in? && @journey.user == current_user %>
    <div class = "navigation-summary-div"
      data-map-target="summary">
      <%= render 'shared/navigation_summary' %>
    </div>
    </div>
    <div class = "navigation-directions-toggle-div"
      data-action="click->navigation-ui#switch">
      <%= render 'shared/directions_toggle' %>
    </div>
  <% end %>

app/views/shared/_navigation_back_button.html.erb
<%# Need both icons do not delete %>
<%# <div class = "nav-back-button-div">
  <%= link_to root_path do %>
    <%# <i class="fas fa-chevron-circle-left"></i> %>
    <%# <i class="fas fa-circle"></i> %>
  <%# <% end %>
<%# </div> %>

<%= link_to root_path do %>
<div class = "test-nav-button-div">
  <i class="fas fa-chevron-left"></i>
</div>
<% end %>

app/views/shared/_navigation_bottom_menu.html.erb
<div class= "nav-bottom-menu-div">
  <div class = "nav-bottom-buttons-div">
    <% if signed_in? && @journey.user == current_user %>
      <%= link_to finish_journey_path(@journey) do %>
        <button class="button-white">I'm here</button>
      <% end %>
      <button type="button" class="button-sos" data-toggle="modal" data-target="#policeModal" data-controller="emergency" data-emergency-target="button">SOS</button>
    <% else %>
      <h3 style="color: white;">You are following <%= @journey.user.full_name %> </h3>
    <% end %>

    <%#Button to call 911%>

  </div>
</div>

<!-- Confirmation message -->
<div class="modal fade" id="policeModal" tabindex="-1" role="dialog" aria-labelledby="policeModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="policeModalLabel">Are you sure?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        You will be redirected with the police.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="tel:+34627841248"><button type="button" class="btn btn-danger" >Call</button></a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navigation_pane.html.erb
<div class="navigation-pane h-100" data-controller="map">
  <%= render 'shared/map' %>
  <%= render 'shared/directions' %>
</div>

app/views/shared/_navigation_right_buttons.html.erb
<div class="nav-right-buttons-div">
  <ul class = "nav-right-icons-list" data-controller="messaging" data-journey-id="<%= @journey.id %>" data-messaging-target="journey">
  <%# Call %>
    <li class = "icon-white-circle" ><span class="iconify button-call icon-backg" data-icon="el:phone-alt" style="color: #29353D;" data-toggle="modal" data-target="#emergencyModal"></span></li>
  <%# New message%>
    <li data-action="click->messaging#send"><i class="fas fa-comment-dots button-msg icon-navy-circle"></i></li>
  <%# Flag %>
  <li class = "icon-white-circle">
    <span id = "flag-nav-button" class="iconify button-flag icon-backg" data-icon="el:flag-alt" style="color: #29353D;" data-action="click->navigation-ui#flag"></span>
  </li>

   <li class="icon-navy-circle d-none" data-navigation-ui-target = "spinnerButton"><i class="fas fa-spinner button-spinner" ></i></li>
  </ul>
</div>

app/views/shared/_navigation_summary.html.erb
<div class="nav-summary-div">
  <i class="fas fa-clock clock-icon-nav-summary"></i>
  <p id="eta" ></p>
  <i class="fas fa-walking walking-icon-nav-summary"></i>
  <p id="distance"></p>
</div>