config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root to: 'pages#home'
  get "/splash", to: "pages#splash"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :update,:edit, :destroy] do
    resources :contacts, only: [:create, :update, :destroy]
  end

  resources :incidents, only: [:new, :create, :edit, :update, :destroy] do
    get "/survey_success", to: "pages#survey_success"
  end

  resources :journeys, only:[:create, :show] do
    member do
      post :broadcast
      get :finish
    end
    resources :incidents, only: [:index, :edit, :update]
  end

  resources :ratings, only: [:create, :index]

  resources :messages, only: :create

  get "/calling", to: "pages#calling"
  get "/navigation", to: "pages#navigation"
  get "/uikit", to: "pages#uikit"
  get "/survey_success", to: "pages#survey_success"
  get "/emergency_number/:iso", to: "emergency_numbers#show"
end

app/views/pages/calling.html.erb
<div class="container my-3">
  <h1>Emergency contacts</h1>
</div>

app/views/pages/home.html.erb
<div class = "wrapper-home">
  <%= render 'shared/logo' %>

  <% if user_signed_in? %>
    <% if current_user.avatar.attached? %>
      <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle avatar-home", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% else %>
      <%= image_tag "Women Power - Avatar.png", class: "avatar dropdown-toggle avatar-home", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% end %>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
      <%= link_to "My profile",  edit_user_registration_path, class: "dropdown-item" %>
      <%= link_to "Log out",   destroy_user_session_path, method: :delete, class: "dropdown-item" %>
    </div>
  <% end %>
  <%# Autocomplete input forms and button %>
  <div class="home-div-inputs">
    <%= simple_form_for Journey.new do |f| %>
        <input name="origin" class="home-input-location" id = "home-input-start" placeholder= "Start location">
        <input name="destination" class="home-input-location" id = "home-input-destination" placeholder= "Destination" >
        <%= f.input :share_location, as: :boolean, label: "Share location with contacts", input_html: {class: "d-none location-box"}, label_html: {class: "location-toggle"}%>
        <button type="submit" class="button-blue"> GO GIRL </button>
    <% end %>
  </div>

  <%# Pattern %>
  <%= image_tag "navyhomepattern.svg", class: "home-page-pattern" %>

 <%# Flag card  %>
  <%= link_to new_incident_path(@incident) do %>
    <div class = "home-flag-card">
      <p> Flag an incident </p>
      <span class="iconify button-flag" data-icon="el:flag-alt" style="color: #29353D;"></span>
    </div>
  <% end %>
</div>

app/views/pages/navigation.html.erb
<div class="map-wrapper" data-navigation-ui-target="container" data-controller="navigation-ui" data-journey-id="<%= @journey.id %>">
  <% if signed_in? && @journey.user == current_user %>
      <%= render 'shared/navigation_back_button' %>

    <div class = "navigation-right-buttons-div">
      <%= render 'shared/navigation_right_buttons' %>
    </div>
    <%= render 'shared/navigation_bottom_menu' %>
    <div class = "navigation-pane-div">
      <%= render 'shared/navigation_pane' %>
    </div>
  <% else %>
    <div class="navigation-pane h-100" data-controller="map">
      <%= render 'shared/map' %>
    </div>
  <% end %>
</div>

<div class=" modal fade" id="emergencyModal" tabindex="-1" role="dialog" aria-labelledby="emergencyModalLabel" aria-hidden="true">
  <div class="modal-dialog " role="document">
    <div class="modal-content modal-back dropdown-box d-inline-flex">
      <div class="title">
        <h5 class="modal-title" id="emergencyModalLabel">Select an emergency contact:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body d-flex flex-column justify-content-center call-dropdown col-12 contacts-list">
        <% @contacts.each do |contact| %>
          <a class="button-contacts text-center mb-2" style="text-decoration:none" href="tel:<%= contact.phone_number %>"> <%= contact.first_name.capitalize %> <%= contact.last_name.capitalize %></a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/splash.html.erb
<div class="splash-container">
  <div class="splash-header">
    <h1 style="font-size:54px"><strong>Go Girl</h1></strong>
    <p style="font-size:20px;color:white"> <strong>Get home safe!</strong> </p>
  </div>

  <div class="circle">
    <%= image_tag("splash_page.png") %>
  </div>

  <div class="splash-buttons">
    <%= link_to new_user_session_path do %>
      <button style="color: white;">LOG IN</button>
    <% end %>
    <%= link_to new_user_registration_path do %>
      <button style="margin-top: 20px;color:white;">SIGN UP</button>
    <% end %>
  </div>
</div>

app/views/pages/survey.html.erb
<div class="survey container">
  <div class="head-message">
    <div class="title-exitbtn">
      <h1>How was your trip?</h1>
      <i class="fas fa-times-circle" style="font-size: 25px; margin-bottom: 8px;"></i>
    </div>
    <p>If you feel comfortable, please complete this optional survey to help us get other users home safely. <br>Your data will be collected anonymously, but it will be displayed on the map so other users know which areas to avoid.</p>
  </div>
  <%= simple_form_for @incident do |f| %>
    <div class="survey-form">
      <div class="custom-field">
      <h3>Where did it happen?</h3>
      <%= f.input :location, label: false, input_html: {class: "form-inputs"},
      wrapper_html: {class: "no-paragraph" } %>
      </div>
      <div class="custom-field">
        <h3>What date did it happen on?</h3>
        <%= f.input :date, label: false, input_html: {class: "form-inputs custom-date"}, wrapper_html: {class: "time-wrapper no-paragraph"} %>
      </div class="custom-field">
      <div>
        <h3>What time did it happen at?</h3>
        <p>If you aren’t sure, choose the nearest estimate.</p>
        <%= f.input :time, label: false, input_html: {class: "form-inputs custom-date"}, wrapper_html: {class: "time-wrapper"} %>
      </div>
      <div class="custom-field">
        <h3>What was the nature of the incident?</h3>
        <p>Select all the categories that apply. If none apply, choose the closest category.</p>
        <%= f.input :crime, collection: ["Catcalling", "Harrassing", "Robbery"], label: false, input_html: {class: "form-inputs"} %>
      </div>
      <div class="custom-field">
        <h3>Additional description:</h3>
        <p>If you have any other information that you want to share, please feel free to write it here. Ie, what did the person look like?  </p>
        <%= f.input :description, as: :text, input_html: {rows: 5, class: "form-inputs"}, label: false %>
      </div>
      <%= f.submit 'Submit my survey response', class: "custom-submit" %>
    </div>
  <% end %>
</div>

app/views/pages/survey_success.html.erb
<% if @journey %>

  <%# Whole page if from journey %>
  <div class="survey-success">
    <%= image_tag "survey.png", class: "survey-img" %>
    <h2>Your response has been submitted!</h2>
    <p>Thank you for taking the time to complete the survey.
    Every response counts!</p>

    <%= link_to root_path do %>
      <button class="button-blue"> Go back home </button>
    <% end %>

    <%= link_to journey_incidents_path(@journey) do %>
      <button class="button-blue success-incidents-button">Return to list of incidents</button>
    <% end %>
  </div>

<% else %>

  <%# Whole page if from home %>
  <div class="survey-success">
    <%= image_tag "survey.png", class: "survey-img-home" %>
    <h2>Your response has been submitted!</h2>
    <p>Thank you for taking the time to complete the survey.
    Every response counts!</p>

    <%= link_to root_path do %>
      <button class="button-blue"> Go back home </button>
    <% end %>
  </div>

<% end %>

app/views/pages/uikit.html.erb
<div class="container">
<form id="login" onsubmit="process(event)">
  <p>Enter your phone number:</p>
  <input type="submit" class="btn" value="Verify" />
</form>

</div>